#!/bin/bash
#
# Start/Stop the SIE DNS sensor.
#
# chkconfig: 2345 99 60
# description: SIE DNS sensor
# processname: nmsgtool
# config: /etc/default/sie-dns-sensor
# pidfile: /var/run/nmsgtool.pid

### BEGIN INIT INFO
# Provides: sie_dns_sensor
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

. /etc/init.d/functions
. /etc/default/sie-dns-sensor
. /usr/lib/sie/functions
 
DESC="SIE DNS sensor"
PIDFILE="/var/run/nmsgtool.pid"

if [ -z "$memory_ulimit_kbytes" ]; then
    memory_ulimit_kbytes="524288"
fi

ulimit -d $memory_ulimit_kbytes
ulimit -m $memory_ulimit_kbytes
ulimit -v $memory_ulimit_kbytes

is_running() {
    if [ -f $PIDFILE ]; then
        checkpid $(cat $PIDFILE)
        return $?
    fi
    return 1
}

start() {
    if ! check_sie_config ; then
        echo -n $"sie-dns-sensor: unable to start."
        failure $"sie-dns-sensor: unable to start."
        echo
        return 1
    fi

    if ! is_running ; then
        prepare_nmsgtool_environment $PIDFILE
        echo -n $"Starting $DESC: "
        daemon nmsgtool
        echo
    fi
}

stop() {
    echo -n $"Stopping $DESC: "
    killproc nmsgtool
    echo
}

restart() {
    stop
    start
}

reload() {
    restart
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload)
        reload
        ;;
    restart)
        restart
        ;;
    status)
        status -p $PIDFILE nmsgtool
        ;;
    condrestart)
        if is_running ; then
            restart
        fi
        ;;
    *)
    echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
    exit 1
esac
